FROM risingstack/alpine:3.3-v4.2.6-1.1.3

RUN apk add --update  bash

RUN /usr/bin/npm install ws

EXPOSE 8082

COPY server.js /usr/src/node-app/
COPY package.json /usr/src/node-app/
WORKDIR /usr/src/node-app/

RUN npm install

ENTRYPOINT ["/usr/bin/node", "/usr/src/node-app/server.js"]

